export const TOPSALES_REQUEST = 'TOPSALES_REQUEST';
export const TOPSALES_SUCCES = 'TOPSALES_SUCCES';
export const TOPSALES_FAILURE = 'TOPSALES_FAILURE';

export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_SUCCES = 'CATEGORIES_SUCCES';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';

export const CATALOG_REQUEST = 'CATALOG_REQUEST';
export const CATALOG_SUCCES = 'CATALOG_SUCCES';
export const CATALOG_FAILURE = 'CATALOG_FAILURE';

export const CHANGE_SEARCH_FIELD   = 'CHANGE_SEARCH_FIELD';

export const CHOSE_CATEGORY = 'CHOSE_CATEGORY';

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCES = 'PRODUCT_SUCCES';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';

export const PRODUCT_COUNTER_INCREMENT = 'PRODUCT_COUNTER_INCREMENT';
export const PRODUCT_COUNTER_DECREMENT = 'PRODUCT_COUNTER_DECREMENT';

export const PRODUCT_SIZE_SELECTED = 'PRODUCT_SIZE_SELECTED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CART_RESET = 'CART_RESET';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const CART_ORDER_REQUEST = 'CART_ORDER_REQUEST';
export const CART_ORDER_SUCCES = 'CART_ORDER_SUCCES';
export const CART_ORDER_FAILURE = 'CART_ORDER_FAILURE';

export const FAVORITE_SELECT = 'FAVORITE_SELECT';